### ISSUE TITLE
almost all examples are broken as following, win 10 , go 1.14

### ISSUE THREAD

**Issue by skydig** [sciter-sdk/go-sciter#249]
08>08.exe
2020/09/17 12:00:12 Unhandled sciter event case: 32768
panic: Unhandled sciter event case: 32768

goroutine 1 [running]:
log.Panic(0xc000073c60, 0x2, 0x2)
        c:/go/src/log/log.go:351 +0xb3
github.com/sciter-sdk/go-sciter.goElementEventProc(0x0, 0x0, 0x8000, 0xb7f5d0, 0x38)
        C:/Users/ssyp/go-sciter/vendor/github.com/sciter-sdk/go-sciter/sciter.go:1468 +0x300
github.com/sciter-sdk/go-sciter._cgoexpwrap_29ac64e236ed_goElementEventProc(0x0, 0x0, 0x8000, 0xb7f5d0, 0x0)
        _cgo_gotypes.go:2000 +0x50
syscall.Syscall(0x7ffc1b8a33b0, 0x2, 0x60164, 0x5, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/runtime/syscall_windows.go:188 +0xe9
github.com/lxn/win.ShowWindow(0x60164, 0xc000000005, 0xc000088000)
        C:/Users/ssyp/go-sciter/vendor/github.com/lxn/win/user32.go:3273 +0x6a
github.com/sciter-sdk/go-sciter/window.(*Window).Show(0xc00002e430)
        C:/Users/ssyp/go-sciter/vendor/github.com/sciter-sdk/go-sciter/window/window_windows.go:42 +0x45
main.main()
        C:/Users/ssyp/go-sciter/examples/demoes/08/demo9.go:59 +0x11a

**Comment by jqqjj** [comment]
Here is the solution。
[https://blog.elmi.page/tag/sciter](url)
