### ISSUE TITLE
the example crash

### ISSUE THREAD

**Issue by wangcheng711** [sciter-sdk/go-sciter#298]
D:\work\go-sciter\examples\callback>callback.exe
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime: unknown pc 0xdb9b0e
stack: frame={sp:0xb239ff640, fp:0x0} stack=[0x0,0xb239ff6f0)
0000000b239ff540:  0000000000000000  00007ff979450000
0000000b239ff550:  0000000000eacd40  0000000000000000
0000000b239ff560:  0000000000db9c91  00007ff9c3edaeac
0000000b239ff570:  0000000000000000  0000000000000000
0000000b239ff580:  0000000000eacd71  00007ff9c3f1672f
0000000b239ff590:  0000000000000000  0000000000db9c91
0000000b239ff5a0:  00000000000a0009  0000000000eacd40
0000000b239ff5b0:  0000000000d4b545 <runtime.callbackasm+5>  0000000000db9c98
0000000b239ff5c0:  00007ff979450000  00007ff97982bc10
0000000b239ff5d0:  0000000000000000  0000000000dbe5f0
0000000b239ff5e0:  0000000000000296  0000000000dba341
0000000b239ff5f0:  000000c0000d5e70  0000000000d4939e <runtime.asmstdcall+94>
0000000b239ff600:  0000000000eb4d98  00007ff900000000
0000000b239ff610:  000000c0000d5e28  0000000000eb4940
0000000b239ff620:  000000c0000d6000  000000c0000d5de8
0000000b239ff630:  000000c000022001  0000000000db9b0e
0000000b239ff640: <000000c00002b000  0000000000002000
0000000b239ff650:  000000c000080000  0000000b239ff678
0000000b239ff660:  0000000000000000  0000000b239ff6b8
0000000b239ff670:  000000c0000d5e28  0000000000eb4940
0000000b239ff680:  000000c0000d5e28  0000000000d477f3 <runtime.asmcgocall+115>
0000000b239ff690:  0000014ae306cd10  0000000000000010
0000000b239ff6a0:  0000000000de9ee0  0000000000de9ee0
0000000b239ff6b0:  000000c0000d5a20  0000000000000248
0000000b239ff6c0:  000000c00003a000  0000000000d1cea0 <runtime.mstart+0>
0000000b239ff6d0:  0000014ae31c1380  0000000000d45c0c <runtime.rt0_go+332>
0000000b239ff6e0:  0000014ae31c1380  0000000000d45c13 <runtime.rt0_go+339>
runtime: unknown pc 0xdb9b0e
stack: frame={sp:0xb239ff640, fp:0x0} stack=[0x0,0xb239ff6f0)
0000000b239ff540:  0000000000000000  00007ff979450000
0000000b239ff550:  0000000000eacd40  0000000000000000
0000000b239ff560:  0000000000db9c91  00007ff9c3edaeac
0000000b239ff570:  0000000000000000  0000000000000000
0000000b239ff580:  0000000000eacd71  00007ff9c3f1672f 
0000000b239ff590:  0000000000000000  0000000000db9c91
0000000b239ff5a0:  00000000000a0009  0000000000eacd40
0000000b239ff5b0:  0000000000d4b545 <runtime.callbackasm+5>  0000000000db9c98
0000000b239ff5c0:  00007ff979450000  00007ff97982bc10
0000000b239ff5d0:  0000000000000000  0000000000dbe5f0
0000000b239ff5e0:  0000000000000296  0000000000dba341
0000000b239ff5f0:  000000c0000d5e70  0000000000d4939e <runtime.asmstdcall+94>
0000000b239ff600:  0000000000eb4d98  00007ff900000000
0000000b239ff610:  000000c0000d5e28  0000000000eb4940
0000000b239ff620:  000000c0000d6000  000000c0000d5de8
0000000b239ff630:  000000c000022001  0000000000db9b0e
0000000b239ff640: <000000c00002b000  0000000000002000
0000000b239ff650:  000000c000080000  0000000b239ff678
0000000b239ff660:  0000000000000000  0000000b239ff6b8
0000000b239ff670:  000000c0000d5e28  0000000000eb4940
0000000b239ff680:  000000c0000d5e28  0000000000d477f3 <runtime.asmcgocall+115>
0000000b239ff690:  0000014ae306cd10  0000000000000010
0000000b239ff6a0:  0000000000de9ee0  0000000000de9ee0
0000000b239ff6b0:  000000c0000d5a20  0000000000000248
0000000b239ff6c0:  000000c00003a000  0000000000d1cea0 <runtime.mstart+0>
0000000b239ff6d0:  0000014ae31c1380  0000000000d45c0c <runtime.rt0_go+332>
0000000b239ff6e0:  0000014ae31c1380  0000000000d45c13 <runtime.rt0_go+339>

goroutine 1 [syscall]:
github.com/sciter-sdk/go-sciter._Cfunc_SciterCreateWindow(0x296, 0xdbe5f0, 0xd4b545, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:485 +0x50
github.com/sciter-sdk/go-sciter.CreateWindow.func1(0x296, 0xdbe5f0, 0xd4b545, 0x0, 0x0, 0x30)
        D:/gocode/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter_windows.go:51 +0x8d
github.com/sciter-sdk/go-sciter.CreateWindow(0x296, 0x0, 0xd4b545, 0x0, 0x0, 0xc000028800)
        D:/gocode/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter_windows.go:51 +0x65
github.com/sciter-sdk/go-sciter/window.New(0x200000296, 0x0, 0xc0000d5f78, 0xce6deb, 0xc000086058)
        D:/gocode/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/window/window_windows.go:24 +0xa5
main.main()
        D:/work/go-sciter/examples/callback/callback.go:12 +0x3d
rax     0x0
rbx     0xc0000d5e28
rcx     0x296
rdi     0xc0000d6000
rsi     0xeb4940
rbp     0xc0000d5de8
rsp     0xb239ff638
r8      0xd4b545
r9      0x0
r10     0x0
r11     0xb239ff2a0
r12     0xc000022001
r13     0x88
r14     0x1
r15     0xc000022000
rip     0x0
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

**Comment by pravic** [comment]
#297 most likely.

**Comment by yunfengwangluo** [comment]
I have the same problem! I don't know how to solve the problem. Although I know it's the sciter API version update, there's nothing I can do for me!!!

**Comment by steampoweredtaco** [comment]
I found if you download the windows dll at this commit it'll work https://github.com/c-smile/sciter-js-sdk/blob/c27c5679d79ee94db8730ce06a7cda2bf5d3daba/bin/windows/x64/sciter.dll

**Comment by Scythemen** [comment]
> I found if you download the windows dll at this commit it'll work https://github.com/c-smile/sciter-js-sdk/blob/c27c5679d79ee94db8730ce06a7cda2bf5d3daba/bin/windows/x64/sciter.dll

You save my life
