### ISSUE TITLE
Segmentation fault on Linux/ARM

### ISSUE THREAD

**Issue by SebDE** [sciter-sdk/go-sciter#303]
I try to built one of the examples (demo2) on my embedded system (32bit ARM, Debian, go 1.15.5, go-sciter master, sciter.JS-sdk 4.4.7.4, ScApp also works)
The build works without a problem, but if I try to start I got the following error

```
root@imx6ul-var-dart:~/test2# ./test2 
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0xe49ab, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x5c
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:726 +0x398

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xba8e4, 0x1828728, 0x8)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5c fp=0x1828710 sp=0x18286f8 pc=0x17cd8
github.com/sciter-sdk/go-sciter._Cfunc_SciterCreateWindow(0x296, 0x172260, 0x0, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:1041 +0x38 fp=0x1828724 sp=0x1828710 pc=0xb0e58
github.com/sciter-sdk/go-sciter.CreateWindow.func1(0x296, 0x172260, 0x0, 0x0, 0x1810128)
	/root/go/src/github.com/sciter-sdk/go-sciter/sciter_linux.go:26 +0x88 fp=0x1828744 sp=0x1828724 pc=0xb6480
github.com/sciter-sdk/go-sciter.CreateWindow(0x296, 0x172260, 0x0, 0x0, 0x0, 0x1edb8)
	/root/go/src/github.com/sciter-sdk/go-sciter/sciter_linux.go:26 +0x3c fp=0x182875c sp=0x1828744 pc=0xb52f4
github.com/sciter-sdk/go-sciter/window.New(0x296, 0x172260, 0x0, 0x1, 0x48668)
	/root/go/src/github.com/sciter-sdk/go-sciter/window/window_linux.go:31 +0x54 fp=0x1828788 sp=0x182875c pc=0xb7cbc
main.main()
	/root/test2/test2.go:107 +0x2c fp=0x18287b8 sp=0x1828788 pc=0xb8664
runtime.main()
	/usr/local/go/src/runtime/proc.go:204 +0x208 fp=0x18287e4 sp=0x18287b8 pc=0x486a4
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:857 +0x4 fp=0x18287e4 sp=0x18287e4 pc=0x740b0
root@imx6ul-var-dart:~/test2#
```

I'm not very familiar with cgo so at the moment I have no idea at which point I got a problem. Can someone point me in the right direction. Many thanks

**Comment by SebDE** [comment]
If I use sciter.JS-sdk 4.4.6.7 everything is okay - Sorry for the issue
Duplicate of #297
