### ISSUE TITLE
Exit status 3221225477

### ISSUE THREAD

**Issue by pierrelh** [sciter-sdk/go-sciter#309]
Hi ! I'm having a problem when running a sciter example or any other kind of project with sciter.
When running "go run main.go" I just have this message : exit status 3221225477.
I'm on windows 10 so to set up sciter I've downloaded the sdk & extract the bin\windows\x64\sciter.dll to C:\windows\system32.
My Go version is 1.15.7 & Gcc version is 8.1.0.
Do you have any hints on what I'm doing wrong ?
Thanks !

**Comment by pravic** [comment]
Any other messages?

**Comment by pierrelh** [comment]
Unfortunatly no, this is the only message I got.
To be sure I'm currently updating Golang & Gcc and I think I'm having PATH issues so I'm trying to fix that to take that appart of the problem.

**Comment by pierrelh** [comment]
So now I'm on Go 1.16.5 & gcc 10.3.0 and here's the error: 
```
C:/tdm-gcc-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: warning: resolving _ElementEventProc_cgo by linking to _ElementEventProc_cgo@16
Use --enable-stdcall-fixup to disable these warnings
Use --disable-stdcall-fixup to disable these fixups
C:/tdm-gcc-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: warning: resolving _LPCBYTE_RECEIVER_cgo by linking to _LPCBYTE_RECEIVER_cgo@12
C:/tdm-gcc-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: warning: resolving _LPCSTR_RECEIVER_cgo by linking to _LPCSTR_RECEIVER_cgo@12
C:/tdm-gcc-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: warning: resolving _LPCWSTR_RECEIVER_cgo by linking to _LPCWSTR_RECEIVER_cgo@12
C:/tdm-gcc-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: warning: resolving _SciterElementCallback_cgo by linking to _SciterElementCallback_cgo@8
C:/tdm-gcc-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: warning: resolving _SciterHostCallback_cgo by linking to _SciterHostCallback_cgo@8
exit status -1
```

**Comment by pierrelh** [comment]
Hi again ! So my environment is now (supposedly) clean, and my others apps using Gcc works. I keep having errors but I don't know where to post them, here or at the go repo directly because in the error I have this error:
`runtime: unknown pc 0x3aa00e`

wich seems to be really go installation / configuration related.
But in the other hand I got this message:
```
goroutine 1 [syscall]:
github.com/sciter-sdk/go-sciter._Cfunc_SciterCreateWindow(0x80, 0x3af5f0, 0x33bd45, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:485 +0x50
github.com/sciter-sdk/go-sciter.CreateWindow.func1(0x80, 0x3af5f0, 0x33bd45, 0x0, 0x0, 0x30)
        C:/Users/lhopi/go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter_windows.go:51 +0x8d
github.com/sciter-sdk/go-sciter.CreateWindow(0x80, 0x0, 0x33bd45, 0x0, 0x0, 0x20)
        C:/Users/lhopi/go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter_windows.go:51 +0x65
github.com/sciter-sdk/go-sciter/window.New(0xc000000080, 0x0, 0xc00003a000, 0x300000002, 0xc00003a000)
        C:/Users/lhopi/go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/window/window_windows.go:24 +0xa5
main.main()
        C:/Users/lhopi/go/src/go-sciter-master/examples/simple/simple.go:13 +0x4b
```

Any ideas ?

Here's the full error: 
```
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime: unknown pc 0x3aa00e
stack: frame={sp:0x7a715ff910, fp:0x0} stack=[0x0,0x7a715ff9c0)
0000007a715ff810:  0000000000000000  00007ffba3130000
0000007a715ff820:  000000000049da60  0000000000000000
0000007a715ff830:  00000000003aa191  00007ffbf56f53dc
0000007a715ff840:  0000000000000000  0000000000000000
0000007a715ff850:  000000000049da91  00007ffbf576869f
0000007a715ff860:  0000000000000000  00000000003aa191
0000007a715ff870:  00000000000a0009  000000000049da60
0000007a715ff880:  000000000033bd45 <runtime.callbackasm+5>  00000000003aa198
0000007a715ff890:  00007ffba3130000  00007ffba350cd60
0000007a715ff8a0:  0000000000000000  00000000003af5f0
0000007a715ff8b0:  0000000000000080  00000000003aa841
0000007a715ff8c0:  000000c00010fe30  0000000000339b9e <runtime.asmstdcall+94>
0000007a715ff8d0:  00000000004a5dc0  00007ffb00000000
0000007a715ff8e0:  000000c00010fde8  00000000004a5960
0000007a715ff8f0:  000000c000110000  000000c00010fda8
0000007a715ff900:  000000c000022001  00000000003aa00e
0000007a715ff910: <000000c00002b000  0000000000002000
0000007a715ff920:  000000c000080000  0000007a715ff948
0000007a715ff930:  0000000000000000  0000007a715ff988
0000007a715ff940:  000000c00010fde8  00000000004a5960
0000007a715ff950:  000000c00010fde8  0000000000337ff3 <runtime.asmcgocall+115>
0000007a715ff960:  000001fcfe9caf50  0000000000000010
0000007a715ff970:  00000000003dade0  00000000003dade0
0000007a715ff980:  000000c00010fa20  0000000000000288
0000007a715ff990:  000000c00003a000  000000000030d640 <runtime.mstart+0>
0000007a715ff9a0:  000001fcfea713c0  000000000033640c <runtime.rt0_go+332>
0000007a715ff9b0:  000001fcfea713c0  0000000000336413 <runtime.rt0_go+339>
runtime: unknown pc 0x3aa00e
stack: frame={sp:0x7a715ff910, fp:0x0} stack=[0x0,0x7a715ff9c0)
0000007a715ff810:  0000000000000000  00007ffba3130000
0000007a715ff820:  000000000049da60  0000000000000000
0000007a715ff830:  00000000003aa191  00007ffbf56f53dc
0000007a715ff840:  0000000000000000  0000000000000000
0000007a715ff850:  000000000049da91  00007ffbf576869f
0000007a715ff860:  0000000000000000  00000000003aa191
0000007a715ff870:  00000000000a0009  000000000049da60
0000007a715ff880:  000000000033bd45 <runtime.callbackasm+5>  00000000003aa198
0000007a715ff890:  00007ffba3130000  00007ffba350cd60
0000007a715ff8a0:  0000000000000000  00000000003af5f0
0000007a715ff8b0:  0000000000000080  00000000003aa841
0000007a715ff8c0:  000000c00010fe30  0000000000339b9e <runtime.asmstdcall+94>
0000007a715ff8d0:  00000000004a5dc0  00007ffb00000000
0000007a715ff8e0:  000000c00010fde8  00000000004a5960
0000007a715ff8f0:  000000c000110000  000000c00010fda8
0000007a715ff900:  000000c000022001  00000000003aa00e
0000007a715ff910: <000000c00002b000  0000000000002000
0000007a715ff920:  000000c000080000  0000007a715ff948
0000007a715ff930:  0000000000000000  0000007a715ff988
0000007a715ff940:  000000c00010fde8  00000000004a5960
0000007a715ff950:  000000c00010fde8  0000000000337ff3 <runtime.asmcgocall+115>
0000007a715ff960:  000001fcfe9caf50  0000000000000010
0000007a715ff970:  00000000003dade0  00000000003dade0 
0000007a715ff980:  000000c00010fa20  0000000000000288
0000007a715ff990:  000000c00003a000  000000000030d640 <runtime.mstart+0>
0000007a715ff9a0:  000001fcfea713c0  000000000033640c <runtime.rt0_go+332>
0000007a715ff9b0:  000001fcfea713c0  0000000000336413 <runtime.rt0_go+339>

goroutine 1 [syscall]:
github.com/sciter-sdk/go-sciter._Cfunc_SciterCreateWindow(0x80, 0x3af5f0, 0x33bd45, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:485 +0x50
github.com/sciter-sdk/go-sciter.CreateWindow.func1(0x80, 0x3af5f0, 0x33bd45, 0x0, 0x0, 0x30)
        C:/Users/lhopi/go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter_windows.go:51 +0x8d
github.com/sciter-sdk/go-sciter.CreateWindow(0x80, 0x0, 0x33bd45, 0x0, 0x0, 0x20)
        C:/Users/lhopi/go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter_windows.go:51 +0x65
github.com/sciter-sdk/go-sciter/window.New(0xc000000080, 0x0, 0xc00003a000, 0x300000002, 0xc00003a000)
        C:/Users/lhopi/go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/window/window_windows.go:24 +0xa5
main.main()
        C:/Users/lhopi/go/src/go-sciter-master/examples/simple/simple.go:13 +0x4b
rax     0x0
rbx     0xc00010fde8
rcx     0x80
rdi     0xc000110000
rsi     0x4a5960
rsp     0x7a715ff908
r8      0x33bd45
r9      0x0
r10     0x0
r11     0x7a715ff560
r12     0xc000022001
r13     0x88
r14     0x1
r15     0xc000022000
rip     0x0
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
exit status 2
```

**Comment by pierrelh** [comment]
Same as #298 but still don't know how to fix it.

**Comment by steampoweredtaco** [comment]
I found if you download the windows dll at this commit it'll work https://github.com/c-smile/sciter-js-sdk/blob/c27c5679d79ee94db8730ce06a7cda2bf5d3daba/bin/windows/x64/sciter.dll

**Comment by pierrelh** [comment]
Yep, I confirm what @steampoweredtaco say, thanks !

**Comment by jackjameshoward** [comment]
I had the same issue.
This also worked for me.
But why did this work, what's broken between windows sciter.dll version 4.4.6.8 to 4.4.8.4 ?
