### ISSUE TITLE
Exception 0xc0000005 0x8 0x0 0x0 PC=0x0 signal arrived during external code execution

### ISSUE THREAD

**Issue by longtian66** [sciter-sdk/go-sciter#312]
when I run the demo simple.go,it's show:

Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
signal arrived during external code execution
github.com/sciter-sdk/go-sciter._Cfunc_SciterCreateWindow(0x296, 0xa115f0, 0x9858c5, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:989 +0x53
github.com/sciter-sdk/go-sciter.CreateWindow.func1(0x296, 0xa115f0, 0x9858c5, 0x0, 0x0, 0x0)
	C:/Users/FLX/go/src/github.com/sciter-sdk/go-sciter/sciter_windows.go:51 +0xcb
github.com/sciter-sdk/go-sciter.CreateWindow(0x296, 0xa115f0, 0x9858c5, 0x0, 0x0, 0x0)
	C:/Users/FLX/go/src/github.com/sciter-sdk/go-sciter/sciter_windows.go:51 +0x87
github.com/sciter-sdk/go-sciter/window.New(0x296, 0x0, 0x0, 0x0, 0x0)
	C:/Users/FLX/go/src/github.com/sciter-sdk/go-sciter/window/window_windows.go:24 +0xd7
main.main()
	e:/FLX-New/src/simple.go:12 +0x6a
rax     0x7ff832d2add0
rbx     0x296
rcx     0x296
rdi     0x9858c5
rsi     0xa115f0
rbp     0x0
rsp     0x76d1fff948
r8      0x9858c5
r9      0x0
r10     0x0
r11     0x76d1fff5f0
r12     0x1eb60e39422
r13     0x0
r14     0x20
r15     0x48
rip     0x0
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
could not remove e:\FLX-New\src\debug: remove e:\FLX-New\src\debug: Access is denied.
Process exiting with code: 0

how can i fix than problem?

**Comment by piaoxue1949** [comment]
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime: unknown pc 0x70e916
stack: frame={sp:0xf2fefff7e0, fp:0x0} stack=[0x0,0xf2fefff900)
0x000000f2fefff6e0:  0x0000000000000000  0x00007ffde3561c42 
0x000000f2fefff6f0:  0x0000ab0145453c17  0x00007ffde5c06777 
0x000000f2fefff700:  0x000000f2fefff750  0x0000000000000020 
0x000000f2fefff710:  0x000000c00003a000  0x0000000000000000 
0x000000f2fefff720:  0x000000c0000cdcc0  0x00007ffd67b20000 
0x000000f2fefff730:  0x00000000007db93b  0x0000000000000000 
0x000000f2fefff740:  0x000000000070e1cf  0x00007ffde35353dc 
0x000000f2fefff750:  0x0000000000000000  0x0000000000000000 
0x000000f2fefff760:  0x00000000007db930  0x00007ffde35a8bcf 
0x000000f2fefff770:  0x000000c000000000  0x000000000070e1cf 
0x000000f2fefff780:  0x00000000000a0009  0x00000000007db93b 
0x000000f2fefff790:  0x000000c0000cdd18  0x000000000070e1e0 
0x000000f2fefff7a0:  0x000000c0000cdd18  0x00007ffd67b41f30 
0x000000f2fefff7b0:  0x000000f2fefff7d0  0x00000000007e38a0 
0x000000f2fefff7c0:  0x00007ffd67b41f30  0x00007ffd67b20000 
0x000000f2fefff7d0:  0x000000f2fefff810  0x000000000070e916 
0x000000f2fefff7e0: <0x0000000000000000  0x0000000000670830 <runtime.(*consistentHeapStats).release+0x0000000000000030> 
0x000000f2fefff7f0:  0x0000000002030000  0x0000000002030000 
0x000000f2fefff800:  0x0000000000000000  0x000000f2fefff870 
0x000000f2fefff810:  0x000000f2fefff870  0x000000000070de35 
0x000000f2fefff820:  0x000000c000000296  0x0000000000718600 
0x000000f2fefff830:  0x00000000006a5aea <runtime.callbackasm+0x000000000000000a>  0x0000000000000000 
0x000000f2fefff840:  0x0000000000000000  0x0000000000002000 
0x000000f2fefff850:  0x000002d11f8dcb78  0x000000c000028800 
0x000000f2fefff860:  0x000000c0000ce000  0x000000c0000cdd18 
0x000000f2fefff870:  0x000000c0000cdcb8  0x00000000006a2133 <runtime.asmcgocall+0x0000000000000073> 
0x000000f2fefff880:  0x000000c0000cdd18  0x0000000000000001 
0x000000f2fefff890:  0x0000000000682900 <runtime.gfget+0x0000000000000160>  0x290000000075e570 
0x000000f2fefff8a0:  0x0000000000000001  0x0000000000000378 
0x000000f2fefff8b0:  0x000000c00003a000  0x000000c0000cd928 
0x000000f2fefff8c0:  0x00000000006a018e <runtime.systemstack+0x000000000000004e>  0x00000000006a47f0 <runtime.newproc+0x0000000000000030> 
0x000000f2fefff8d0:  0x0000000000000000  0x000000f2fefef968 
runtime: unknown pc 0x70e916
stack: frame={sp:0xf2fefff7e0, fp:0x0} stack=[0x0,0xf2fefff900)
0x000000f2fefff6e0:  0x0000000000000000  0x00007ffde3561c42 
0x000000f2fefff6f0:  0x0000ab0145453c17  0x00007ffde5c06777 
0x000000f2fefff700:  0x000000f2fefff750  0x0000000000000020 
0x000000f2fefff710:  0x000000c00003a000  0x0000000000000000 
0x000000f2fefff720:  0x000000c0000cdcc0  0x00007ffd67b20000 
0x000000f2fefff730:  0x00000000007db93b  0x0000000000000000 
0x000000f2fefff740:  0x000000000070e1cf  0x00007ffde35353dc 
0x000000f2fefff750:  0x0000000000000000  0x0000000000000000 
0x000000f2fefff760:  0x00000000007db930  0x00007ffde35a8bcf 
0x000000f2fefff770:  0x000000c000000000  0x000000000070e1cf 
0x000000f2fefff780:  0x00000000000a0009  0x00000000007db93b 
0x000000f2fefff790:  0x000000c0000cdd18  0x000000000070e1e0 
0x000000f2fefff7a0:  0x000000c0000cdd18  0x00007ffd67b41f30 
0x000000f2fefff7b0:  0x000000f2fefff7d0  0x00000000007e38a0 
0x000000f2fefff7c0:  0x00007ffd67b41f30  0x00007ffd67b20000 
0x000000f2fefff7d0:  0x000000f2fefff810  0x000000000070e916 
0x000000f2fefff7e0: <0x0000000000000000  0x0000000000670830 <runtime.(*consistentHeapStats).release+0x0000000000000030> 
0x000000f2fefff7f0:  0x0000000002030000  0x0000000002030000 
0x000000f2fefff800:  0x0000000000000000  0x000000f2fefff870 
0x000000f2fefff810:  0x000000f2fefff870  0x000000000070de35 
0x000000f2fefff820:  0x000000c000000296  0x0000000000718600 
0x000000f2fefff830:  0x00000000006a5aea <runtime.callbackasm+0x000000000000000a>  0x0000000000000000 
0x000000f2fefff840:  0x0000000000000000  0x0000000000002000 
0x000000f2fefff850:  0x000002d11f8dcb78  0x000000c000028800 
0x000000f2fefff860:  0x000000c0000ce000  0x000000c0000cdd18 
0x000000f2fefff870:  0x000000c0000cdcb8  0x00000000006a2133 <runtime.asmcgocall+0x0000000000000073> 
0x000000f2fefff880:  0x000000c0000cdd18  0x0000000000000001 
0x000000f2fefff890:  0x0000000000682900 <runtime.gfget+0x0000000000000160>  0x290000000075e570 
0x000000f2fefff8a0:  0x0000000000000001  0x0000000000000378 
0x000000f2fefff8b0:  0x000000c00003a000  0x000000c0000cd928 
0x000000f2fefff8c0:  0x00000000006a018e <runtime.systemstack+0x000000000000004e>  0x00000000006a47f0 <runtime.newproc+0x0000000000000030> 
0x000000f2fefff8d0:  0x0000000000000000  0x000000f2fefef968 

goroutine 1 [syscall]:
runtime.cgocall(0x70dde6, 0xc0000cdd18)
	G:/Program Files/go/src/runtime/cgocall.go:156 +0x4a fp=0xc0000cdcc8 sp=0xc0000cdc90 pc=0x643baa
github.com/sciter-sdk/go-sciter._Cfunc_SciterCreateWindow(0x296, 0x718600, 0x6a5aea, 0x0, 0x0)
	_cgo_gotypes.go:485 +0x5b fp=0xc0000cdd18 sp=0xc0000cdcc8 pc=0x703e5b
github.com/sciter-sdk/go-sciter.CreateWindow.func1(0x296, 0x718600, 0x6a5aea, 0x0, 0x0)
	F:/work/Go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter_windows.go:51 +0xd9 fp=0xc0000cdd98 sp=0xc0000cdd18 pc=0x708139
github.com/sciter-sdk/go-sciter.CreateWindow(0x296, 0x718600, 0x6a5aea, 0x0, 0x0)
	F:/work/Go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter_windows.go:51 +0x8e fp=0xc0000cde10 sp=0xc0000cdd98 pc=0x707fce
github.com/sciter-sdk/go-sciter/window.New(0x296, 0x0)
	F:/work/Go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/window/window_windows.go:24 +0xa7 fp=0xc0000cded8 sp=0xc0000cde10 pc=0x70aa27
main.main()
	F:/work/程序/go/program/src/sciter_test/main.go:18 +0x45 fp=0xc0000cdf80 sp=0xc0000cded8 pc=0x70af25
runtime.main()
	G:/Program Files/go/src/runtime/proc.go:255 +0x1d7 fp=0xc0000cdfe0 sp=0xc0000cdf80 pc=0x67a2f7
runtime.goexit()
	G:/Program Files/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000cdfe8 sp=0xc0000cdfe0 pc=0x6a24c1
rax     0x718600
rbx     0xc0000cdd18
rcx     0x296
rdi     0xc0000cdd18
rsi     0x7e38a0
rbp     0xf2fefff810
rsp     0xf2fefff7d8
r8      0x6a5aea
r9      0x0
r10     0x0
r11     0xf2fefff470
r12     0xc0000cdcc0
r13     0x0
r14     0xc00003a000
r15     0x20
rip     0x0
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

调试器 已完成，退出代码为 0

**Comment by zoulee24** [comment]
there is no gui show 
runing demo01 i got Process finished with the exit code -1073741819 (0xC0000005)

**Comment by lysShub** [comment]
maybe you use sciter.js's dll/so , should tis sdk

**Comment by kioley** [comment]
same error on examples https://github.com/sciter-sdk/go-sciter/blob/master/examples

```
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
signal arrived during external code execution

runtime.cgocall(0x44c0c0, 0xc0000d1e20)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x4a fp=0xc0000d1df8 sp=0xc0000d1dc0 pc=0x39406a
github.com/sciter-sdk/go-sciter._Cfunc_SciterCreateWindow(0x296, 0xc0000ae110, 0x3f1b4a, 0x0, 0x0)
        _cgo_gotypes.go:489 +0x5b fp=0xc0000d1e20 sp=0xc0000d1df8 pc=0x44571b
github.com/sciter-sdk/go-sciter.CreateWindow.func1(0x30?, 0x0?, 0x30?, 0x6?, 0x0?)
        C:/Users/kiole/go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter_windows.go:51 +0x79 fp=0xc0000d1e88 sp=0xc0000d1e20 pc=0x4483f9
github.com/sciter-sdk/go-sciter.CreateWindow(0x47c5a0?, 0x49ab48?, 0x53abc0?, 0xc0000ae110?, 0x0?)
        C:/Users/kiole/go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter_windows.go:51 +0x25 fp=0xc0000d1ec0 sp=0xc0000d1e88 pc=0x448305
github.com/sciter-sdk/go-sciter/window.New(0x296, 0xc0000a83b0?)
        C:/Users/kiole/go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/window/window_windows.go:24 +0x71 fp=0xc0000d1f28 sp=0xc0000d1ec0 pc=0x449e31
main.main()
        C:/Users/kiole/Downloads/sciter-sdk go-sciter master examples-demoes_01/main.go:19 +0xd4 fp=0xc0000d1f80 sp=0xc0000d1f28 pc=0x44a194
runtime.main()
        C:/Program Files/Go/src/runtime/proc.go:250 +0x1fe fp=0xc0000d1fe0 sp=0xc0000d1f80 pc=0x3c779e
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000d1fe8 sp=0xc0000d1fe0 pc=0x3ee741
rax     0x0
rbx     0xc0000d1e20
rcx     0x296
rdi     0xc0000d2000
rsi     0x53a860
rbp     0xc0000d1de8
rsp     0x5d471ff508
r8      0x3f1b4a
r9      0x0
r10     0x0
r11     0x5d471ff160
r12     0xc000020000
r13     0xc000020000
r14     0xc000034000
r15     0x2
rip     0x0
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
exit status 2
```
