### ISSUE TITLE
Can't build and run the simple sample on Ubuntu

### ISSUE THREAD

**Issue by Immortalt** [sciter-sdk/go-sciter#315]
Ubuntu 20.04
go version go1.15.14 linux/amd64
I switched to go 1.15 for that 1.16 cannot install.
But after installation, I still cannot even build and run the simple sample.
Here is the error:
```
GOROOT=/snap/go/7950 #gosetup
GOPATH=/home/lenovo/go #gosetup
/snap/go/7950/bin/go build -o /tmp/___go_build_github_com_sciter_sdk_go_sciter_examples_simple github.com/sciter-sdk/go-sciter/examples/simple #gosetup
/tmp/___go_build_github_com_sciter_sdk_go_sciter_examples_simple #gosetup
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x4f81d4, 0x2a)
	/snap/go/7950/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/snap/go/7950/src/runtime/signal_unix.go:726 +0x4ac

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4bdf90, 0xc00004ae40, 0x7fd3f75b9a20)
	/snap/go/7950/src/runtime/cgocall.go:133 +0x5b fp=0xc00004ae10 sp=0xc00004add8 pc=0x40a1db
github.com/sciter-sdk/go-sciter._Cfunc_SciterCreateWindow(0x296, 0x594f30, 0x0, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:1042 +0x4e fp=0xc00004ae40 sp=0xc00004ae10 pc=0x4b576e
github.com/sciter-sdk/go-sciter.CreateWindow.func1(0x296, 0x594f30, 0x0, 0x0, 0xc000098200)
	/home/lenovo/go/src/github.com/sciter-sdk/go-sciter/sciter_linux.go:26 +0x9d fp=0xc00004ae88 sp=0xc00004ae40 pc=0x4b8f7d
github.com/sciter-sdk/go-sciter.CreateWindow(0x296, 0x0, 0x0, 0x0, 0x0, 0xc000000001)
	/home/lenovo/go/src/github.com/sciter-sdk/go-sciter/sciter_linux.go:26 +0x4c fp=0xc00004aec0 sp=0xc00004ae88 pc=0x4b852c
github.com/sciter-sdk/go-sciter/window.New(0x296, 0x0, 0xc000000180, 0xc00004af78, 0x40cbc5)
	/home/lenovo/go/src/github.com/sciter-sdk/go-sciter/window/window_linux.go:31 +0x68 fp=0xc00004af20 sp=0xc00004aec0 pc=0x4bb208
main.main()
	/home/lenovo/go/src/github.com/sciter-sdk/go-sciter/examples/simple/simple.go:12 +0x36 fp=0xc00004af88 sp=0xc00004af20 pc=0x4bb876
runtime.main()
	/snap/go/7950/src/runtime/proc.go:204 +0x209 fp=0xc00004afe0 sp=0xc00004af88 pc=0x43c8c9
runtime.goexit()
	/snap/go/7950/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00004afe8 sp=0xc00004afe0 pc=0x46b4a1

Process finished with the exit code 2
```

**Comment by ChugunovRoman** [comment]
Same issue

**Comment by aaronchen2k** [comment]
same issue on Mac
