### ISSUE TITLE
Exception：runtime: unknown pc 0x7ff74c219c2e，please help

### ISSUE THREAD

**Issue by amberzizi** [sciter-sdk/go-sciter#319]
go1.16.5
windows
x86_64-6.4.0-release-posix-seh-rt_v5-rev0\mingw64\

Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime: unknown pc 0x7ff74c219c2e
stack: frame={sp:0x4744dff520, fp:0x0} stack=[0x0,0x4744dff5d0)
0000004744dff420:  0000000000000000  00007ff994190000 
0000004744dff430:  00007ff74c3171e0  0000000000000000 
0000004744dff440:  00007ff74c219db1  00007ff9f925ae9c 
0000004744dff450:  0000000000000000  0000000000000000 
0000004744dff460:  00007ff74c317211  00007ff9f929671f 
0000004744dff470:  0000000000000000  00007ff74c219db1 
0000004744dff480:  00000000000a0009  00007ff74c3171e0 
0000004744dff490:  00007ff74c1abd25 <runtime.callbackasm+5>  00007ff74c219db8 
0000004744dff4a0:  00007ff994190000  00007ff9941b1ba4 
0000004744dff4b0:  0000000000000000  00007ff74c2285f0 
0000004744dff4c0:  0000000000000296  00007ff74c21a461 
0000004744dff4d0:  000000c000121e68  00007ff74c1a9b7e <runtime.asmstdcall+94> 
0000004744dff4e0:  00007ff74c31fdc0  00007ff900000000 
0000004744dff4f0:  000000c000121e20  00007ff74c31f960 
0000004744dff500:  000000c000122000  000000c000121de0 
0000004744dff510:  000000c00001c001  00007ff74c219c2e 
0000004744dff520: <0000000000000000  0000000000002000 
0000004744dff530:  00007ff74c181ff5 <runtime.goschedImpl+245>  00007ff74c31f818 
0000004744dff540:  0000000000000000  0000004744dff598 
0000004744dff550:  000000c000121e20  00007ff74c31f960 
0000004744dff560:  000000c000121e20  00007ff74c1a7fd3 <runtime.asmcgocall+115> 
0000004744dff570:  0000023d7c76ad30  0000000000000010 
0000004744dff580:  00007ff74c253de0  00007ff74c253de0 
0000004744dff590:  000000c000121a20  0000000000000250 
0000004744dff5a0:  000000c000048000  00007ff74c17d620 <runtime.mstart+0> 
0000004744dff5b0:  0000000000000001  00007ff74c1a63ec <runtime.rt0_go+332> 
0000004744dff5c0:  0000000000000001  00007ff74c1a63f3 <runtime.rt0_go+339> 
runtime: unknown pc 0x7ff74c219c2e
stack: frame={sp:0x4744dff520, fp:0x0} stack=[0x0,0x4744dff5d0)
0000004744dff420:  0000000000000000  00007ff994190000 
0000004744dff430:  00007ff74c3171e0  0000000000000000 
0000004744dff440:  00007ff74c219db1  00007ff9f925ae9c 
0000004744dff450:  0000000000000000  0000000000000000 
0000004744dff460:  00007ff74c317211  00007ff9f929671f 
0000004744dff470:  0000000000000000  00007ff74c219db1 
0000004744dff480:  00000000000a0009  00007ff74c3171e0 
0000004744dff490:  00007ff74c1abd25 <runtime.callbackasm+5>  00007ff74c219db8 
0000004744dff4a0:  00007ff994190000  00007ff9941b1ba4 
0000004744dff4b0:  0000000000000000  00007ff74c2285f0 
0000004744dff4c0:  0000000000000296  00007ff74c21a461 
0000004744dff4d0:  000000c000121e68  00007ff74c1a9b7e <runtime.asmstdcall+94> 
0000004744dff4e0:  00007ff74c31fdc0  00007ff900000000 
0000004744dff4f0:  000000c000121e20  00007ff74c31f960 
0000004744dff500:  000000c000122000  000000c000121de0 
0000004744dff510:  000000c00001c001  00007ff74c219c2e 
0000004744dff520: <0000000000000000  0000000000002000 
0000004744dff530:  00007ff74c181ff5 <runtime.goschedImpl+245>  00007ff74c31f818 
0000004744dff540:  0000000000000000  0000004744dff598 
0000004744dff550:  000000c000121e20  00007ff74c31f960 
0000004744dff560:  000000c000121e20  00007ff74c1a7fd3 <runtime.asmcgocall+115> 
0000004744dff570:  0000023d7c76ad30  0000000000000010 
0000004744dff580:  00007ff74c253de0  00007ff74c253de0 
0000004744dff590:  000000c000121a20  0000000000000250 
0000004744dff5a0:  000000c000048000  00007ff74c17d620 <runtime.mstart+0> 
0000004744dff5b0:  0000000000000001  00007ff74c1a63ec <runtime.rt0_go+332> 
0000004744dff5c0:  0000000000000001  00007ff74c1a63f3 <runtime.rt0_go+339> 

goroutine 1 [syscall]:
github.com/sciter-sdk/go-sciter._Cfunc_SciterCreateWindow(0x7ff700000296, 0x7ff74c2285f0, 0x7ff74c1abd25, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:485 +0x50
github.com/sciter-sdk/go-sciter.CreateWindow.func1(0x7ff700000296, 0x7ff74c2285f0, 0x7ff74c1abd25, 0x0, 0x0, 0x30)
	D:/golang/dev/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter_windows.go:51 +0x8d
github.com/sciter-sdk/go-sciter.CreateWindow(0x7ff700000296, 0x0, 0x7ff74c1abd25, 0x0, 0x0, 0x7ff74c18312f)
	D:/golang/dev/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter_windows.go:51 +0x65
github.com/sciter-sdk/go-sciter/window.New(0xc000000296, 0x0, 0xc000048000, 0xc000121f78, 0x7ff74c14756b)
	D:/golang/dev/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/window/window_windows.go:24 +0xa5
main.main()
	D:/golang/sim/demo.go:20 +0x3d
rax     0x0
rbx     0xc000121e20
rcx     0x296
rdi     0xc000122000
rsi     0x7ff74c31f960
rbp     0xc000121de0
rsp     0x4744dff518
r8      0x7ff74c1abd25
r9      0x0
r10     0x0
r11     0x4744dff180
r12     0xc00001c001
r13     0x88
r14     0x1
r15     0xc00001c000
rip     0x0
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b

**Comment by wj008** [comment]
https://github.com/wj008/go-sciter 
 for Sciter 4.4.8.0+
